In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[4,5]])

array([[1, 2],
       [4, 5]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
np.asanyarray([2,3,4])

array([2, 3, 4])

In [9]:
b = np.matrix(l)

In [10]:
b

matrix([[1, 2, 3, 4]])

In [11]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [12]:
a = np.array(l)

In [13]:
a

array([1, 2, 3, 4])

In [14]:
c = a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c[0] = 100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
d[0] = 200

In [24]:
d

array([200,   2,   3,   4])

In [25]:
a

array([100,   2,   3,   4])

In [26]:
a[0] = 300

In [27]:
a

array([300,   2,   3,   4])

In [28]:
d

array([200,   2,   3,   4])

In [29]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
np.fromfunction(lambda i,j : i+j, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [133]:
iterable = (i*i for i in range(5))

In [135]:
iterable

<generator object <genexpr> at 0x7f4dd5400900>

In [33]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [139]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [138]:
np.fromstring('4,3', sep = ',')

array([4., 3.])

In [140]:
np.fromstring('3,6,9' , sep = ',')

array([3., 6., 9.])

In [36]:
#Numpy - Data Types.

In [37]:
l = [1,2,3,4]

In [38]:
ar = np.array(l)

In [39]:
ar

array([1, 2, 3, 4])

In [40]:
ar.ndim

1

In [41]:
ar2 = np.array([[1,2,3,4], [4,5,6,7]])

In [42]:
ar2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [43]:
ar2.ndim

2

In [44]:
ar2.dtype

dtype('int64')

In [45]:
ar.dtype

dtype('int64')

In [46]:
ar

array([1, 2, 3, 4])

In [47]:
ar.size

4

In [48]:
ar2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [49]:
ar2.size

8

In [50]:
ar.shape

(4,)

In [51]:
ar2.shape

(2, 4)

In [52]:
ar2.dtype

dtype('int64')

In [53]:
ar22 = np.array([(1,2,3,4.2), (5,6,7,2.1)])

In [141]:
ar22.ndim

2

In [54]:
ar22

array([[1. , 2. , 3. , 4.2],
       [5. , 6. , 7. , 2.1]])

In [55]:
ar22.dtype

dtype('float64')

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
try : 
    list(range(1.1, 5))
except Exception as e : 
    print(e)

'float' object cannot be interpreted as an integer


In [58]:
a = np.arange(2.3, 5)

In [59]:
a

array([2.3, 3.3, 4.3])

In [60]:
a.dtype

dtype('float64')

In [61]:
b = np.arange(2.3, 5.6, .3)

In [62]:
b

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [63]:
list(b)

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [64]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [65]:
type(np.linspace(2,5,10))

numpy.ndarray

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [69]:
ar4 = np.zeros((3,4,2,3))

In [70]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [71]:
ar4.ndim

4

In [72]:
type(ar4)

numpy.ndarray

In [73]:
np.ones(4)

array([1., 1., 1., 1.])

In [74]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
type(np.ones((4,3)))

numpy.ndarray

In [76]:
on = np.ones((2,3,2))

In [77]:
on + 5


array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [78]:
on.ndim

3

In [79]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [80]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [81]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [82]:
np.logspace(3,4, 10, base = 2)

array([ 8.        ,  8.64047791,  9.33223232, 10.0793684 , 10.88632   ,
       11.75787594, 12.69920842, 13.71590373, 14.8139954 , 16.        ])

In [83]:
arr = np.random.randn(3,4)

In [84]:
arr

array([[-0.45362203,  1.52603073,  0.39734115, -2.28320413],
       [-0.38102773,  0.8018746 ,  1.26332516, -0.45568452],
       [ 0.11138062,  1.24486936, -0.56013719, -0.04330546]])

In [85]:
import pandas as pd

In [86]:
pd.DataFrame(arr)

0         1         2         3
0 -0.453622  1.526031  0.397341 -2.283204
1 -0.381028  0.801875  1.263325 -0.455685
2  0.111381  1.244869 -0.560137 -0.043305

In [87]:
ar = np.random.rand(3,4)

In [88]:
pd.DataFrame(ar)

0         1         2         3
0  0.943737  0.261361  0.124112  0.422896
1  0.718838  0.158327  0.267764  0.824246
2  0.337466  0.982403  0.721658  0.776727

In [89]:
pd.DataFrame(np.random.randint(1,110,  (100,200))).to_csv('test.csv')

In [90]:
arr = np.random.rand(3,4)

In [91]:
arr

array([[0.31237407, 0.58523745, 0.62549792, 0.44056782],
       [0.39339529, 0.906626  , 0.23924108, 0.33598712],
       [0.71655876, 0.4199583 , 0.46811777, 0.40283072]])

In [92]:
arr.reshape(6,2)

array([[0.31237407, 0.58523745],
       [0.62549792, 0.44056782],
       [0.39339529, 0.906626  ],
       [0.23924108, 0.33598712],
       [0.71655876, 0.4199583 ],
       [0.46811777, 0.40283072]])

In [93]:
arr.reshape(6,-1)

array([[0.31237407, 0.58523745],
       [0.62549792, 0.44056782],
       [0.39339529, 0.906626  ],
       [0.23924108, 0.33598712],
       [0.71655876, 0.4199583 ],
       [0.46811777, 0.40283072]])

In [94]:
arr = arr.reshape(6,-14134234234)

In [95]:
arr

array([[0.31237407, 0.58523745],
       [0.62549792, 0.44056782],
       [0.39339529, 0.906626  ],
       [0.23924108, 0.33598712],
       [0.71655876, 0.4199583 ],
       [0.46811777, 0.40283072]])

In [96]:
arr[2][1]

0.9066259970219193

In [97]:
arr[2,1]

0.9066259970219193

In [98]:
arr[2:5 , 1]

array([0.906626  , 0.33598712, 0.4199583 ])

In [99]:
arr = np.random.randint(1,100 , (5,5))

In [100]:
arr

array([[38, 22, 44, 64, 91],
       [92, 51, 86,  7, 83],
       [78,  1, 67, 24, 70],
       [10, 63,  3, 42, 54],
       [ 6, 66, 22, 12, 60]])

In [101]:
arr[arr>50]

array([64, 91, 92, 51, 86, 83, 78, 67, 70, 63, 54, 66, 60])

In [102]:
arr[1:3, [0,1,2]]

array([[92, 51, 86],
       [78,  1, 67]])

In [103]:
arr[0,0] = 5000

In [104]:
arr

array([[5000,   22,   44,   64,   91],
       [  92,   51,   86,    7,   83],
       [  78,    1,   67,   24,   70],
       [  10,   63,    3,   42,   54],
       [   6,   66,   22,   12,   60]])

In [105]:
ar1 = np.random.randint(1,10, (4,4))

In [106]:
ar2 = np.random.randint(1,10, (4,4))

In [107]:
ar1,ar2

(array([[8, 7, 6, 5],
        [6, 2, 2, 2],
        [2, 9, 1, 8],
        [5, 8, 4, 4]]),
 array([[1, 8, 5, 7],
        [3, 5, 3, 6],
        [8, 4, 6, 1],
        [2, 4, 5, 6]]))

In [108]:
ar1+ar2

array([[ 9, 15, 11, 12],
       [ 9,  7,  5,  8],
       [10, 13,  7,  9],
       [ 7, 12,  9, 10]])

In [109]:
ar1 - ar2

array([[ 7, -1,  1, -2],
       [ 3, -3, -1, -4],
       [-6,  5, -5,  7],
       [ 3,  4, -1, -2]])

In [110]:
ar1 *ar2

array([[ 8, 56, 30, 35],
       [18, 10,  6, 12],
       [16, 36,  6,  8],
       [10, 32, 20, 24]])

In [111]:
ar1/ar2

array([[8.        , 0.875     , 1.2       , 0.71428571],
       [2.        , 0.4       , 0.66666667, 0.33333333],
       [0.25      , 2.25      , 0.16666667, 8.        ],
       [2.5       , 2.        , 0.8       , 0.66666667]])

In [112]:
ar1@ar2

array([[ 87, 143, 122, 134],
       [ 32,  74,  58,  68],
       [ 53,  97,  83, 117],
       [ 69, 112,  93, 111]])

In [113]:
ar1/0

/tmp/ipykernel_116/3042774750.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [114]:
ar1 + 100

array([[108, 107, 106, 105],
       [106, 102, 102, 102],
       [102, 109, 101, 108],
       [105, 108, 104, 104]])

In [115]:
ar1 ** 2

array([[64, 49, 36, 25],
       [36,  4,  4,  4],
       [ 4, 81,  1, 64],
       [25, 64, 16, 16]])

In [116]:
#Numpy - Broadcasting

In [117]:
ar = np.zeros((4,4))

In [118]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
ar1 = np.array([[1,2,3,4]])

In [120]:
ar1

array([[1, 2, 3, 4]])

In [121]:
ar1 + ar

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [122]:
ar1.T 

array([[1],
       [2],
       [3],
       [4]])

In [123]:
ar1.T + ar

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [124]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
ar1

array([[1, 2, 3, 4]])

In [126]:
ar2 = np.random.randint(2,5, (3,4))

In [127]:
ar2

array([[3, 3, 4, 3],
       [4, 3, 2, 2],
       [4, 3, 4, 4]])

In [128]:
np.log2(ar2)

array([[1.5849625, 1.5849625, 2.       , 1.5849625],
       [2.       , 1.5849625, 1.       , 1.       ],
       [2.       , 1.5849625, 2.       , 2.       ]])

In [129]:
np.log10(ar2)

array([[0.47712125, 0.47712125, 0.60205999, 0.47712125],
       [0.60205999, 0.47712125, 0.30103   , 0.30103   ],
       [0.60205999, 0.47712125, 0.60205999, 0.60205999]])

In [130]:
np.exp(ar2)

array([[20.08553692, 20.08553692, 54.59815003, 20.08553692],
       [54.59815003, 20.08553692,  7.3890561 ,  7.3890561 ],
       [54.59815003, 20.08553692, 54.59815003, 54.59815003]])

In [131]:
np.sqrt(ar2)

array([[1.73205081, 1.73205081, 2.        , 1.73205081],
       [2.        , 1.73205081, 1.41421356, 1.41421356],
       [2.        , 1.73205081, 2.        , 2.        ]])

In [132]:
np.conjugate(ar2)

array([[3, 3, 4, 3],
       [4, 3, 2, 2],
       [4, 3, 4, 4]])