In [1]:
#Numpy - Array manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,4 , (3,4))

In [4]:
arr

array([[1, 1, 3, 1],
       [3, 3, 1, 3],
       [2, 1, 3, 2]])

In [5]:
arr.reshape(6,2)

array([[1, 1],
       [3, 1],
       [3, 3],
       [1, 3],
       [2, 1],
       [3, 2]])

In [6]:
arr.reshape(2,6)

array([[1, 1, 3, 1, 3, 3],
       [1, 3, 2, 1, 3, 2]])

In [7]:
arr.reshape(12,1)

array([[1],
       [1],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [2],
       [1],
       [3],
       [2]])

In [8]:
arr.T

array([[1, 3, 2],
       [1, 3, 1],
       [3, 1, 3],
       [1, 3, 2]])

In [9]:
arr

array([[1, 1, 3, 1],
       [3, 3, 1, 3],
       [2, 1, 3, 2]])

In [10]:
arr.flatten()

array([1, 1, 3, 1, 3, 3, 1, 3, 2, 1, 3, 2])

In [11]:
arr1 = np.array([1,2,3,4,5])

In [12]:
arr1

array([1, 2, 3, 4, 5])

In [13]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 4, 5]])

In [15]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
arr = np.array([[1], [2], [3]])

In [17]:
arr

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(arr)

array([1, 2, 3])

In [19]:
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [20]:
np.roll(arr, 2)

array([[2],
       [3],
       [1]])

In [21]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
#Numpy - Binary Operators.

In [23]:
ar1 = np.random.randint(1,10 , (3,4))

In [24]:
ar2 = np.random.randint(1,10 , (3,4))

In [25]:
ar1

array([[2, 9, 8, 7],
       [7, 3, 6, 1],
       [3, 1, 6, 1]])

In [26]:
ar2

array([[3, 4, 3, 4],
       [6, 2, 6, 7],
       [8, 2, 3, 3]])

In [27]:
ar1 + ar2

array([[ 5, 13, 11, 11],
       [13,  5, 12,  8],
       [11,  3,  9,  4]])

In [28]:
ar1 - ar2

array([[-1,  5,  5,  3],
       [ 1,  1,  0, -6],
       [-5, -1,  3, -2]])

In [29]:
ar1/ ar2

array([[0.66666667, 2.25      , 2.66666667, 1.75      ],
       [1.16666667, 1.5       , 1.        , 0.14285714],
       [0.375     , 0.5       , 2.        , 0.33333333]])

In [30]:
ar1*ar2

array([[ 6, 36, 24, 28],
       [42,  6, 36,  7],
       [24,  2, 18,  3]])

In [31]:
ar1&ar2

array([[2, 0, 0, 4],
       [6, 2, 6, 1],
       [0, 0, 2, 1]])

In [32]:
ar1%ar2

array([[2, 1, 2, 3],
       [1, 1, 0, 1],
       [3, 1, 0, 1]])

In [33]:
ar1>ar2

array([[False,  True,  True,  True],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [34]:
ar1 | ar2

array([[ 3, 13, 11,  7],
       [ 7,  3,  6,  7],
       [11,  3,  7,  3]])

In [35]:
~ar1

array([[ -3, -10,  -9,  -8],
       [ -8,  -4,  -7,  -2],
       [ -4,  -2,  -7,  -2]])

In [36]:
#Numpy - String Functions.

In [37]:
arr = np.array(['ujjwal', 'Ram'])

In [38]:
arr

array(['ujjwal', 'Ram'], dtype='<U6')

In [39]:
np.char.upper(arr)

array(['UJJWAL', 'RAM'], dtype='<U6')

In [40]:
np.char.title(arr)

array(['Ujjwal', 'Ram'], dtype='<U6')

In [41]:
np.char.capitalize(arr)

array(['Ujjwal', 'Ram'], dtype='<U6')

In [42]:
#Numpy - Mathematical Functions.

In [43]:
arr1

array([1, 2, 3, 4, 5])

In [44]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [45]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [46]:
np.tan(arr1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [49]:
np.mean(arr1)

3.0

In [51]:
np.median(arr1)

3.0

In [52]:
np.var(arr1)

2.0

In [53]:
np.tanh(arr1)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [54]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [56]:
np.power(arr1,2)

array([ 1,  4,  9, 16, 25])

In [57]:
np.exp(arr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [58]:
np.max(arr1)

5

In [59]:
np.min(arr1)


1