In [1]:
#Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [4]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [5]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [42]:
np.searchsorted(arr,5)

8

In [7]:
arr1 = np.array([0,0,24,2412,21,0,0,0,124,0,412])

In [8]:
arr1

array([   0,    0,   24, 2412,   21,    0,    0,    0,  124,    0,  412])

In [9]:
np.count_nonzero(arr1)

5

In [10]:
arr


array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [11]:
np.where(arr > 5)

(array([ 4,  5,  8, 10, 11]),)

In [12]:
np.extract( arr > 5 , arr)

array([  6,  72, 455,   6,   6])

In [13]:
#Numpy - Byte Swapping.

In [14]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [15]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [16]:
#Numpy - Copies &Views.

In [17]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [18]:
a = np.copy(arr)

In [19]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
a[0] = 100

In [21]:
a

array([100,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
b = arr.view()

In [24]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [26]:
b[2] = 200

In [27]:
b

array([  4,   3, 200,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [28]:
arr

array([  4,   3, 200,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [29]:
#Numpy - Matrix Library.

In [30]:
import numpy.matlib as nm

In [31]:
nm.zeros(3)

matrix([[0., 0., 0.]])

In [32]:
nm.ones((4,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
nm.eye(3,3) 

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
#Numpy - Linear Algebra

In [35]:
arr1 = np.random.randint(1,10, (5,5))

In [36]:
arr2 = np.random.randint(1,10, (5,5))

In [37]:
arr1,arr2

(array([[9, 3, 4, 4, 7],
        [9, 1, 9, 2, 6],
        [1, 6, 3, 9, 1],
        [8, 3, 5, 9, 4],
        [1, 5, 5, 1, 3]]),
 array([[4, 4, 7, 5, 5],
        [7, 8, 5, 2, 5],
        [7, 5, 5, 5, 9],
        [1, 9, 2, 6, 6],
        [7, 5, 8, 7, 7]]))

In [38]:
arr1@arr2

array([[138, 151, 162, 144, 169],
       [150, 137, 165, 146, 185],
       [ 83, 153,  78,  93, 123],
       [125, 182, 146, 153, 182],
       [ 96,  93,  83,  67, 102]])

In [39]:
np.dot(arr1,arr2)

array([[138, 151, 162, 144, 169],
       [150, 137, 165, 146, 185],
       [ 83, 153,  78,  93, 123],
       [125, 182, 146, 153, 182],
       [ 96,  93,  83,  67, 102]])